kind: pipeline
type: docker
name: go-api-deploy

steps:
  - name: quality
    image: golang:1.24-alpine
    commands:
      - go mod download
      - go vet ./config/... ./migrations/... ./fixtures/... .
      - gofmt -d .
      - test -z "$(gofmt -l .)"

  - name: build
    image: golang:1.24-alpine
    commands:
      - go mod tidy
      - go test ./config/... ./migrations/... ./fixtures/... .
      - go build -o bab-insa-api main.go
      - go build -o migrate-binary cmd/migrate/migrate.go
      - go build -o fixtures-binary cmd/fixtures/fixtures.go
    depends_on:
      - quality

  - name: deploy-staging
    image: alpine:3
    commands:
      - apk update && apk upgrade
      - apk add openssh bash rsync
      - mkdir -p ~/.ssh
      - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_ed25519
      - printf "Host *\n  StrictHostKeyChecking no\n  UserKnownHostsFile=/dev/null\n" > ~/.ssh/config
      - chmod 600 ~/.ssh/id_ed25519
      - eval $(ssh-agent -s)
      - ssh-add ~/.ssh/id_ed25519
      - rsync -rav --quiet --exclude='.env' -e "ssh -p $STAGING_SSH_PORT" bab-insa-api migrate-binary fixtures-binary $STAGING_SSH_USER@$STAGING_SSH_HOST:$STAGING_PATH/
      - ssh -p $STAGING_SSH_PORT $STAGING_SSH_USER@$STAGING_SSH_HOST "chmod +x $STAGING_PATH/bab-insa-api $STAGING_PATH/migrate-binary $STAGING_PATH/fixtures-binary"
      - ssh -p $STAGING_SSH_PORT $STAGING_SSH_USER@$STAGING_SSH_HOST "pkill -f bab-insa-api || true && cd $STAGING_PATH && nohup ./bab-insa-api > /dev/null 2>&1 & echo 'Service restarted'"
    environment:
      SSH_PRIVATE_KEY:
        from_secret: staging_ssh_key
      STAGING_SSH_PORT:
        from_secret: staging_ssh_port
      STAGING_SSH_HOST:
        from_secret: staging_ssh_host
      STAGING_SSH_USER:
        from_secret: staging_ssh_user
      STAGING_PATH:
        from_secret: staging_path
    depends_on:
      - build
    when:
      branch:
        - dev

  - name: deploy-production
    image: alpine:3
    commands:
      - apk update && apk upgrade
      - apk add openssh bash rsync
      - mkdir -p ~/.ssh
      - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_ed25519
      - printf "Host *\n  StrictHostKeyChecking no\n  UserKnownHostsFile=/dev/null\n" > ~/.ssh/config
      - chmod 600 ~/.ssh/id_ed25519
      - eval $(ssh-agent -s)
      - ssh-add ~/.ssh/id_ed25519
      - rsync -av --quiet --exclude='.env' -e "ssh -p $PRODUCTION_SSH_PORT" bab-insa-api migrate-binary $PRODUCTION_SSH_USER@$PRODUCTION_SSH_HOST:$PRODUCTION_PATH/
      - ssh -p $PRODUCTION_SSH_PORT $PRODUCTION_SSH_USER@$PRODUCTION_SSH_HOST "chmod +x $PRODUCTION_PATH/bab-insa-api $PRODUCTION_PATH/migrate-binary"
      - ssh -p $PRODUCTION_SSH_PORT $PRODUCTION_SSH_USER@$PRODUCTION_SSH_HOST "pkill -f bab-insa-api || true && cd $PRODUCTION_PATH && nohup ./bab-insa-api > /dev/null 2>&1 & echo 'Service restarted'"
    environment:
      SSH_PRIVATE_KEY:
        from_secret: production_ssh_key
      PRODUCTION_SSH_PORT:
        from_secret: production_ssh_port
      PRODUCTION_SSH_HOST:
        from_secret: production_ssh_host
      PRODUCTION_SSH_USER:
        from_secret: production_ssh_user
      PRODUCTION_PATH:
        from_secret: production_path
    depends_on:
      - build
    when:
      branch:
        - main

trigger:
  branch:
    - dev
    - main